### ISSUE TITLE
如何添加 Web User

### ISSUE THREAD

**Issue by COOlJJJ** [MrGaoGang/mrgaogang.github.io#1]
我希望通过账号密码登录Mendix app.
在本地添加的Local User,当Mnedix 发布到Free Cloud上之后，就无法使用了.
![image](https://user-images.githubusercontent.com/32292341/100051121-1045b100-2e56-11eb-820e-9ea91574a5ba.png)
我尝试添加web service user,但是仍然无法登录.

**Comment by MrGaoGang** [comment]
> 我希望通过账号密码登录Mendix app.
> 在本地添加的Local User,当Mnedix 发布到Free Cloud上之后，就无法使用了.
> ![image](https://user-images.githubusercontent.com/32292341/100051121-1045b100-2e56-11eb-820e-9ea91574a5ba.png)
> 我尝试添加web service user,但是仍然无法登录.

本地建立的user发布到cloud时无法使用的哦，需要在cloud端重新配置

**Comment by COOlJJJ** [comment]
好的,谢谢。
