### ISSUE TITLE
Mendix Web端如何调用摄像头

### ISSUE THREAD

**Issue by COOlJJJ** [MrGaoGang/mrgaogang.github.io#2]
尝试使用Mendix提供的Camera组件,无法实现调用.提示错误信息 "Unable to detect camera.",不知道怎么解决。难道网页版本无法调取摄像头吗?

**Comment by MrGaoGang** [comment]
> 尝试使用Mendix提供的Camera组件,无法实现调用.提示错误信息 "Unable to detect camera.",不知道怎么解决。难道网页版本无法调取摄像头吗?

网页是可以调用摄像头的，得具体看一下你是手机端使用还是PC，如果是PC的话是目前是不支持的，移动端是可以的

**Comment by COOlJJJ** [comment]
好的，谢谢.
